import MainHeader from "@/components/layout/MainHeader";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export type Children = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Children) {
	return (
		<html lang="en">
			<body>
				<MainHeader />
				<div className="pt-20 max-w-6xl m-auto">{children}</div>
			</body>
		</html>
	);
}
